### ISSUE TITLE
Add a dependency on DataFrames?

### ISSUE THREAD

**Issue by dmbates** [palday/MixedModelsMakie.jl#17]
In exploring the `lattice::xyplot` types of plots I find it helps to work with a `GroupedDataFrame` so I was going to write methods that work with them.  This will necessitate adding a dependency on `DataFrames`, which I will do in a branch.

It may turn out that this is not a good place to put such code and we may split it off to a separate package at some future time.

**Comment by palday** [comment]
I'm fine with depending on `DataFrames` for now. If we find a nice way to drop that dependency in the future, that's fine, but it's also not something I'm worried about.

**Comment by palday** [comment]
I'm now using DataFrames in #28, so we can consider this acceptance of using DataFrames for now :smile:
