### ISSUE TITLE
ridgeplot! doesn't have default keys

### ISSUE THREAD

**Issue by Tokazama** [palday/MixedModelsMakie.jl#43]
Recently got this error

```julia
julia> ridgeplot!(g_porb_ndi[1,1], boot_porb_ndi);
ERROR: KeyError: key :conf_level not found
```

It works if I set the key word arguments `conf_level` and `show_intercept` manually, but I figured these were supposed to have default values like `ridgeplot`

**Comment by palday** [comment]
Huh, I'm not sure exactly why that doesn't work. I know why it works for `ridgeplot`, but I thought [the recipe set the default values](https://github.com/palday/MixedModelsMakie.jl/blob/7275e6413875f39dd4775408cf49aaf62b4528d7/src/ridge.jl#L2-L8). 

I will have take another deep dive into recipes to understand this behavior, so it might be a while before this is fixed.

**Comment by jmmanley** [comment]
Some related kwarg weirdness with the auto-generated `ridgeplot!` method: although they are required, `conf_level` and `vline_at_zero` don't seem to do anything. But `show_intercept` seems to work.

```julia
m1 = fit(MixedModel,
         @formula(1000 / reaction ~ 1 + days + (1 + days | subj)),
         MixedModels.dataset(:sleepstudy))

nsamp = 1000
bootstrap = parametricbootstrap(nsamp, m1)

conf_level=0.95
vline_at_zero=true
show_intercept=true

fig = Figure(; resolution=(1200, 400))
ax1 = Axis(fig[1, 1]; title="just ridgeplot!")
ridgeplot!(ax1, bootstrap; conf_level, vline_at_zero, show_intercept)

ax2 = Axis(fig[1, 2]; title="ridgeplot! and coefplot!")
ridgeplot!(ax2, bootstrap; conf_level, vline_at_zero, show_intercept)
coefplot!(ax2, bootstrap; conf_level, vline_at_zero, show_intercept)
save("test.png", fig)
```

![test](https://github.com/palday/MixedModelsMakie.jl/assets/11412376/3e9d1795-30b3-48e2-8a30-5d4402f3ca2e)

**Comment by palday** [comment]
@jmmanley which Makie/CairoMakie version are you using?

**Comment by jmmanley** [comment]
@palday I originally observed this with
```
  [13f3f980] CairoMakie v0.10.12
  [ff71e718] MixedModels v4.22.3
  [b12ae82c] MixedModelsMakie v0.3.27
```

and also reproduced it in a fresh environment with just
```
  [13f3f980] CairoMakie v0.11.6
  [ff71e718] MixedModels v4.22.3
  [b12ae82c] MixedModelsMakie v0.3.28
```
