### ISSUE TITLE
Changing attributes of caterpillar plots

### ISSUE THREAD

**Issue by venkatasg** [palday/MixedModelsMakie.jl#73]
I'm using this library to plot and visualize random and fixed effects, and am trying to change the appearance of the plots. Currently it looks like the mean of the random effects is plotted with an alpha value of 0.2 for markers, and I would like to change that for my plots to be more visible. How does one go about doing this? It doesn't look like I can access the attributes of the scatterplot that is created within `caterpillar!`. I've figured out how to change the `label` and `title` in a very hacky way like so:

```
c = caterpillar!(f, ranefinfo(model)[:ranef1])
c.content[1].title = "impression_item_index random intercept estimates"
c.content[1].xlabel = ""
```

Is there a similar hacky way to access the attributes?

**Comment by palday** [comment]
A new release will be out in 20-30 minutes which adds `dotcolor` as a keyword argument.
